name: Prepare Python environment
description: Setup python, poetry, SpatialLite and install dependencies

runs:
  using: composite
  steps:
    - name: Install spatialLite
      run: |
        sudo apt-get update && sudo apt-get install -y \
          spatialite-bin \
          libsqlite3-mod-spatialite
      shell: bash

    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.8.*'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        cache: poetry

    - name: Install dependencies
      run: poetry install --no-root
      shell: bash

