name: Prepare Python environment
description: Setup python, uv and install dependencies

runs:
  using: composite
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: uv sync --frozen --no-install-project
      shell: bash

