name: "Reusable workflow: Create release"

on:
  workflow_call:
    inputs:
      increment:
        description: Increment
        type: string
        required: false
        default: minor
      generate_release_notes:
        description: Generate release notes
        required: false
        type: boolean
        default: false
      body:
        description: Description of changes
        required: false
        type: string
    secrets:
      APPLICATION_ID:
        description: Application id for creating release
        required: true
      APPLICATION_PRIVATE_KEY:
        description: Application private key for creating release
        required: true

jobs:
  create-release:
    name: Create ${{ inputs.increment }} release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Token for creating new Release
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@dad2b81e50ce3edeb5f3b7ffbd79f731368bd668 # v5.1.1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: "contents:write"
          revoke_token: true

      - name: Get next version
        uses: reecetech/version-increment@28d33de033e97a304f77238d6a5db26039ca15d6 # 2026.8.4
        id: version
        with:
          scheme: semver
          increment: ${{ inputs.increment }}

      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          make_latest: false
          prerelease: ${{ contains(steps.version.outputs.version, '-pre') && 'true' || 'false' }}
          tag_name: ${{ steps.version.outputs.version }}
          token: ${{ steps.get_workflow_token.outputs.token }}
          body: ${{ inputs.body }}
          generate_release_notes: ${{ inputs.generate_release_notes }}
